###
GET http://172.16.5.199:82/api/debug-cache
Accept: application/json

###
GET http://172.16.5.199:82/api/apps/karyawans?noancak=2
Authorization: Bearer 1|tEe3dxPYj0SOWtSz7adjXKxSFMnP6su5UjBMWqpzd57d2cbe
Accept: application/json

###
GET http://172.16.5.199:82/api/apps/karyawans/3603
Authorization: Bearer 1|tEe3dxPYj0SOWtSz7adjXKxSFMnP6su5UjBMWqpzd57d2cbe
Accept: application/json

###
DELETE http://172.16.5.199:82/api/apps/karyawans/3603
Authorization: Bearer 1|tEe3dxPYj0SOWtSz7adjXKxSFMnP6su5UjBMWqpzd57d2cbe
Accept: application/json

###
GET http://dev.skj.my.id:82/api/master/sips-fields
Authorization: Bearer 62|j66hnzb3PFHjEdm97ySFc296ehJ1dP2gdHWNSnhOc1793f68
Accept: application/json

###
GET http://dev.skj.my.id:82/api/logs?start_date=2025-09-21&end_date=2025-09-22&method=GET&per_page=20
Authorization: Bearer 62|j66hnzb3PFHjEdm97ySFc296ehJ1dP2gdHWNSnhOc1793f68
Accept: application/json

###
GET http://dev.skj.my.id:82/api/logs/123
Authorization: Bearer 62|j66hnzb3PFHjEdm97ySFc296ehJ1dP2gdHWNSnhOc1793f68
Accept: application/json